# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-06 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
